### ISSUE TITLE
Hardcoded path to /bin/nvidia-smi

### ISSUE THREAD

**Issue by logix2** [congard/nvidia-system-monitor#2]
Currently nvidia-system-monitor doesn't work on Debian (or Ubuntu, etc.) because the nvidia-smi binary path is hardcoded to /bin/nvidia-smi, while on Debian/Ubuntu it's in /usr/bin/nvidia-smi. As a result, I get this error:
```
$ nvidia-system-monitor 
Connecting to nvidia-smi...
nvidia-smi not found. Are you have NVIDIA drivers?
NVSMApp 0x55f24e528c00 deleted
```

**Comment by congard** [comment]
I have added `/usr/bin/nvidia-smi` to search path. Please, test the latest [master](https://github.com/congard/nvidia-system-monitor) version

**Comment by logix2** [comment]
Somehow I still get the same error with the latest git.

**Comment by congard** [comment]
I replaced `fopen()` with `system()`. Please, test the latest [master](https://github.com/congard/nvidia-system-monitor) version

**Comment by logix2** [comment]
It works now, thanks!
